### ISSUE TITLE
large ifgramstack crashes the 'Output Results to GeoTiff' workbook

### ISSUE THREAD

**Issue by iykman360** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#11]
**Notebook name**
Which notebook contains the bug? Output Results to GeoTiff

**Describe the bug**
A clear and concise description of what the bug is. I created a large volume of interferograms and my ifgramstack is around 33GB. However, when i try to run this line ( _, unw_info = mintpy.utils.readfile.read(ifgramstack)) of section 5 'Save the unwrapped Displacement Geo Tiffs', it crashes the system. 

**To Reproduce**
1. Go to '...'Output Results to GeoTiff' workbook

**Expected behavior**
A clear and concise description of what you expected to happen. I expect this section to run seamlessly. 

**Screenshots**

**Are you running locally or in OpenSARLab?** I am runnig in OpenSARLab 

**System Info (If not working in OpenSARLab):**
 - JupyterLab version
 - opensarlab_MintPy_Recipe_Book Version [e.g. 1.0.0]

**Data**
Details of your InSAR SBAS stack, if applicable to your problem:

**Additional context**

**Comment by Alex-Lewandowski** [comment]
@iykman360 Would you provide some more detail in how it crashes? Does the notebook kernel die? Does your OpenSARLab server stop running? Do you receive an error when trying to run that line? Do you have enough storage space remaining to hold the output GeoTiffs?

**Comment by iykman360** [comment]
Hi Alex, 
Thanks for your response.
My Disk space used is: 20.29%. I think I have enough space remaining to hold the output. 
I have attached the error message
![error](https://github.com/user-attachments/assets/a232ac9b-5771-4394-b43a-b01ca499e1d7)
I think my server stops running because the ifgramstack is too large. Is there a way to read the ifgramstack in batches? Maybe that could work.

**Comment by Alex-Lewandowski** [comment]
Hi @iykman360, Typically, if the stack is too large and you run out of memory, it results in a crashed notebook kernel but the server continues to run. The server can sometimes crash unexpectedly when using a shared server on a JupyterHub (like OpenSARLab). Both the `SAR 1` and `SAR 2` servers profiles are shared. The `m6a.xlarge - Single User` and `m6a.large - Single User` servers are not. I recommend trying one of those.

**Comment by iykman360** [comment]
Thank you so much, Alex. 
This worked !!!
