### ISSUE TITLE
SBAS MintPy for GeoTiff Output data

### ISSUE THREAD

**Issue by rossindk** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#13]
**Is your feature request related to a problem? Please describe.**
I've just start learning about SBAS using MintPy. I'm trying to analyze the deformation of a peatland area from 2020 to 2023. When I use this method, the outputs are in KMZ and .h5 formats. As a beginner, I find it difficult to understand whether the data generated is correct or not, and this is quite confusing for me.

**Describe the solution you'd like**
I would like to obtain the results in raster format (GeoTIFF) for annual deformation and also for each image pair.

**Describe alternatives you've considered**
If obtaining GeoTIFF is not possible, are there other ways to make it easier to read the final results and the unwrapped images in meters?

**Comment by Alex-Lewandowski** [comment]
Hi @rossindk, The notebook https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/blob/main/Output_GeoTiff.ipynb will provide output data as GeoTiffs. It also allows for scaling the interferograms in meters or centimeters.

**Comment by rossindk** [comment]
Thank you for your help. I just obtained the results in GeoTiff and converted it to vector data. I would like to ask if it is possible to achieve higher resolution, and if so, what factors do I need to consider?

In this case, I am using Sentinel-1 imagery. The data I obtained has a resolution of approximately 80m x 80m.
![image](https://github.com/user-attachments/assets/cc3b9e0c-fb3c-4a64-93e5-a61201a7a391)

**Comment by Alex-Lewandowski** [comment]
Hi @rossindk, The resolution will be determined by the resolution of the input interferograms. 

Currently, ASF offers custom InSAR processing on full sentinel-1 scenes (the INSAR_GAMMA product) and also at the burst-level (the INSAR_ISCE_BURST). Full scenes are typically comprised of about 27 bursts. Sentinel-1 scenes can experience frameshift over time, whereas burst locations remain consistent. INSAR_GAMMA data is available in 20x4 (160m) or 10x2 (80m) looks. INSAR_ISCE_BURST data are available in 20x4 (160m), 10x2 (80m), or 5x1 (40m) looks. You can select the number of looks when submitting your HyP3 project on Vertex:

![image](https://github.com/user-attachments/assets/81dbf118-6cd3-457c-b220-b4abbfcc479e)

Using an INSAR_ISCE_BURST SBAS stack processed at 5x1 looks will give you the highest possible resolution from HyP3 data.
