### ISSUE TITLE
Not searching data (Checking all HyP3 projects for current INSAR_GAMMA jobs  is not working)

### ISSUE THREAD

**Issue by Deva234678** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#16]
**Notebook name**
opensarlab_MintPy_Recipe_Book Version

**Describe the bug**
its not checking data from earth data account and table of contents nothing is there

**To Reproduce**
1. Go to 'opensarlab_MintPy_Recipe_Book Version'
2. Click on '3_Access_HyP3_Data'
3. Scroll down to 'cell number 8'
4. See error "NameError                                 Traceback (most recent call last)
Cell In[10], line 11
      7 for project in tqdm(my_hyp3_info['job_names']):
      8         batch = Batch()
      9         batch = hyp3.find_jobs(
     10             name=project, 
---> 11             job_type=product_type
     12         ).filter_jobs(running=False, include_expired=False)
     13         if len(batch) > 0:
     14             active_projects.update({batch.jobs[0].name: batch})

NameError: name 'product_type' is not defined"

**Expected behavior**
"It should fetch data from earth data account. so i can choose my Ondemand HyP3 data"

**Screenshots**
![image](https://github.com/user-attachments/assets/62ef81c1-435f-4e93-b4fb-4038a230c7d8)

**Are you running locally or in OpenSARLab?**
OpenSARLab
**System Info (If not working in OpenSARLab):**
 - JupyterLab version
 - opensarlab_MintPy_Recipe_Book Version [e.g. 1.0.0]

**Data**
Details of your InSAR SBAS stack, if applicable to your problem: Polav_ISCE_1 is the project name

**Additional context**
After this only i can run next step so rectify quickly.

**Comment by Alex-Lewandowski** [comment]
Hi @Deva234678, It appears that you skipped running the proceeding code cell, which initializes the `product_type` variable.

![image](https://github.com/user-attachments/assets/97b82832-64b4-4218-aa00-5e291861396f)

https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/blob/main/3_Access_HyP3_Data.ipynb?short_path=6ddd836#L216-L225
