### ISSUE TITLE
GSLC to generate inteferogram

### ISSUE THREAD

**Issue by Zuga99** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#3]
I am facing issues with generating inteferogram for the GSLC data that I have acquired from NISAR sampla data site. Kindly guide me through this and also let me know which Jupyter notebook to refer for this.

**Comment by Alex-Lewandowski** [comment]
This Jupyter Book currently only handles with Sentinel-1 interferograms processed with [ASF HyP3](https://hyp3-docs.asf.alaska.edu/) 

You can create an interferogram from two NISAR GSLCs by multiplying the complex data from a reference scene by the complex conjugate of the secondary scene. We do not have a notebook in OpenSARLab to do this; however, here is an example using [OPERA](https://www.jpl.nasa.gov/go/opera)'s CSLC data, which is also provided in HDF5 and should be a very similar process: https://github.com/OPERA-Cal-Val/OPERA_Applications/blob/main/CSLC/Discover/Create_Interferogram_by_Streaming_CSLC-S1.ipynb

Please note that this does not include any form of error correction, such as removing phase components related to atmospheric delay. 

NISAR also has a GUNW (geocoded phase unwrapped interferogram) product. The public mirror of the Python wrapper of the code that will be used for that processing can be found here: https://github.com/isce-framework/isce3/tree/develop/python/packages/nisar/products/insar

There is a GUNW sample available as well: https://nisar.jpl.nasa.gov/data/sample-data/

Please be aware that as of today, the two sample NISAR GSLCs found at the above link are identical, and will produce an interferogram showing no phase change. The example GUNW uses different GSLCs, and so does show phase change.
