### ISSUE TITLE
"IndexError: list index out of range", when running "1. Build the opensarlab_mintpy_recipe_book Conda Environment¶"

### ISSUE THREAD

**Issue by SlientR** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#5]
Hi, 

I installed and activated hyp3-docs, using conda; download opensarlab_MintPy_Recipe_Book github, and navigate to it within anaconda, ran "Jupyter notebook, and ran "1_Software_Environment.ipynb", but I got an error of "list out of range", for the command "conda_yaml_pth = list(Path.cwd().glob(yaml_name))[0]". 

Please see the screenshot attached. I highly appreciate your help in resolving the problem;

<img width="451" alt="error" src="https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/169557771/9c3df485-d7ea-4227-b878-a4a04c3f2697">

**Comment by Alex-Lewandowski** [comment]
Hi @SilentR, 

I apologize for not responding sooner! It sounds like you are running this locally. While it was written to run in the OpenSARLab JupyterHub, we would like to support running it on a local computer as well. Can you provide some details about your system and how you are running the notebooks? What operating system are you using? Did you move the notebook to a new directory after cloning the repository? Is there an `environment_locked.yaml` file in the same directory as the notebook? What is the output if you create a new code cell and run the command `!pwd`? How about `!ls`?

**Comment by Alex-Lewandowski** [comment]
@SlientR I am closing this as a stale issue, but please reopen it if you are still having trouble.
