### ISSUE TITLE
Connect component file for missing pair Erorr and .kml export issue

### ISSUE THREAD

**Issue by suatcoskun** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#7]
Today I tried to run MintPy with sentinel-1 Burst datasets for Teton Landslides. I prepared a seasonal stack and I added some custom pairs to bridge the seasons. But when I started Access_HyP3_data.ipyn and subset stacks, I took .geotiff and removed the warning message. 

![1](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/f404d594-2417-40eb-a577-91d187a3c690)

Then I continue the process stacks. But when I tried to run Load_Hyp3_data.ipny step2 (load the data with MintPy) I took the connect component file for missing pair warning and it shut down not continuously. 

![Ekran görüntüsü 2024-06-11 152334](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/6486f6b9-695f-4db1-8d51-67df64383a4c)

![Ekran görüntüsü 2024-06-11 152354](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/497d36eb-b564-4e81-a779-b30e1bae2983)

Then I turned back Access_HyP3 step and deleted the removed .geotiff folder manually  step2 (load the data with MintPy) worked well. 
So I think when Access_HyP3_data.ipyn subsetting stack was not deleted removed geotiff folders and this caused some crash in step2. 

The second interesting thing is about my custom pairs. Because Access_HyP3_data.ipyn (remove any subset scenes containing no data) deleted exactly my custom pairs.

![prep_network](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/ba6429a7-1909-434b-a14f-b52b53c40d6a)
(this is demostiration)

![network_result](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/27aa8787-23c0-4c92-b86c-051d9e5e8c49)

I think these will be bugs.

The last observation about MintPy; .kml export option doesn't work correctly. It doesn't open on Google Earth. I think it will be about different coordinate systems. 

Best…

Suat

**Comment by Alex-Lewandowski** [comment]
Hi Suat, It is interesting that after subsetting, only the connected components of your custom pairs were deleted as containing no data. If you had subset the data to an area containing no data, I would expect that all the geotiffs for that product would be empty as well, and that they would also have been deleted.

In your screenshots, it appears that you are using an old version of the Jupyter Book. We just released an update yesterday. Specifically, I noticed that the cells immediately prior to checking for rasters containing no data after subsetting do not contain the new code, which allows you to convert the data from UTM to WGS84:

<img width="1427" alt="image" src="https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/009d514e-1390-4143-b415-3769877803a1">
 
If you are working locally, I recommend pulling in the recent update.

If you are working in OpenSARLab I recommend stopping and restarting your server, which will sync the repo, pulling in the updates.

The updates include changes to the environment, so you should rerun the `1_Software_Environment.ipynb` notebook. One of the environment updates installs MintPy from a recent commit, which resolves the KMZ issue that you mentioned: [https://github.com/insarlab/MintPy/pull/1210](https://github.com/insarlab/MintPy/pull/1210)

If you still run into trouble after pulling in the update, recreating the environment, and starting the process over by accessing a fresh copy of the data, please let me know and send the following in a private message:
- your HyP3 username
- the name of the HyP3 project containing your data

You can email that to me at aflewandowski@alaska.edu

With that information, I can access the exact dataset you are working with and help debug the issue. 

Best,
Alex

**Comment by Alex-Lewandowski** [comment]
Hi @suatcoskun,

Thank you for sending the details of your HyP3 project. 

I downloaded all 92 interferograms and subsetted to pretty much the entire common area covered by the stack, meaning every subset raster had coverage of the selected AOI:
![image](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/4491fd3f-5587-4bb6-bfd4-83c7024210c9)

No subsets were deleted as empty:
![image](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/e9fab32e-8e24-41d1-b961-f1b00e489348)
 
I was able to load the time series without removing any interferograms:
![image](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/4ea7098f-529f-4ae8-a925-a6c9b11140d6)

I then tried subsetting to an area larger than the rasters, just to see if I could break things, but once again, no rasters were found to be empty and deleted. 

If you continue to have trouble, please email a copy of the data access notebook with all output saved in place so I can attempt to reproduce the problem. I suspect that if there is an issue, it has to do with subsetting. 

Best,
Alex

**Comment by suatcoskun** [comment]
Hi @Alex-Lewandowski 

I continue to have trouble but this time I have an idea what is causing this issue. If you are subsetting stacks like you with a bounding box I have no error message.

![box](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/d832d496-26fa-48cd-9059-aa2821bebe03)

![no_removed](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/8e42fbdc-71e7-4efa-8fb5-bb84aeaf7483)

But if I use a smaller area and .shp file subseting some .tiff files were removed.  

![shp_file](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/36a44eaf-dcff-4503-9ace-d0cca0980d4c)

![result_shp](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/36503613/6db39b49-4174-4ac3-9e1e-07412711416c)


 (I sent my notebook access permission to your mail address.)

Best
Suat

**Comment by Alex-Lewandowski** [comment]
Thanks for the update, @suatcoskun! 

This is very helpful. I'll look into the issue when using a shapefile for subsetting.

**Comment by Alex-Lewandowski** [comment]
Hi @suatcoskun,

Thank you for sending the shapefile you were using. That clarified the source of the problem nicely! 

The connected components ["delineate regions unwrapped as contiguous units by the SNAPHU unwrapping algorithm."](https://hyp3-docs.asf.alaska.edu/guides/burst_insar_product_guide/#:~:text=delineates%20regions%20unwrapped%20as%20contiguous%20units%20by%20the%20SNAPHU%20unwrapping%20algorithm).

No data values in the connected components files are perfectly valid, but we do not account for that in the notebook and end up deleting connected components files filled with nans. 

The connected components for your custom interferograms contain only nans in your AOI, and this why they were being deleted. You can see that there is no data in your AOI in the screenshot of one of the connected components files below:

<img width="840" alt="image" src="https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/c4fcdbeb-3f9e-4ba0-91dd-185ba2d1d31e">

Thank you so much for bringing this to our attention and working with us to identify the source of the problem. I will update the notebook so it does not delete connected components files containing no data if they are accompanied by unwrapped phase rasters that do contain data, as they are valid. 

I will leave this issue open until we release the fix.

**Comment by Alex-Lewandowski** [comment]
Closing as resolved by https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/pull/8
