### ISSUE TITLE
NameError: name 'product_type' is not defined

### ISSUE THREAD

**Issue by iykman360** [ASFOpenSARlab/opensarlab_MintPy_Recipe_Book#9]
**Notebook name**
Which notebook contains the bug? Access_Hyp3_Data.ipynb

**Describe the bug**
Whenever i run section 8, i get this nameError: name 'product_type' is not defined

**To Reproduce**

**Expected behavior**

**Screenshots**
![Uploading error.PNG…]()

**Are you running locally or in OpenSARLab?**

**System Info (If not working in OpenSARLab):**
 - JupyterLab version
 - opensarlab_MintPy_Recipe_Book Version [e.g. 1.0.0]

**Data**
Details of your InSAR SBAS stack, if applicable to your problem:

**Additional context**

**Comment by Alex-Lewandowski** [comment]
Hi @iykman360, It looks like the code cell that defines product_type may have been inadvertently skipped or deleted. It is the cell immediately prior to the cell producing the error, and contains a single line of code:
![image](https://github.com/ASFOpenSARlab/opensarlab_MintPy_Recipe_Book/assets/37909088/46afaa56-3837-4637-a2bf-e1fc11cf4146)

If you are working in OpenSARLab and you think some code cells may have been deleted, you can pull in a fresh copy by deleting the notebook and restarting your OpenSARLab server. The notebook repositories are synced upon start up.

**Comment by iykman360** [comment]
Thank you so much Alex,
This worked!!!

**Comment by Alex-Lewandowski** [comment]
Closing as resolved.
